### ISSUE TITLE
Shutdown and restart do not work, I can only shut down through twrp recovery at a time, and I can't remember to adjust the resolution, and I need to adjust again after each power-up.

### ISSUE THREAD

**Issue by Uchiha-Peng** [droidian-images/rootfs-api28gsi-all#2]
Shutdown and restart do not work, I can only shut down through twrp recovery at a time, and I can't remember to adjust the resolution, and I need to adjust again after each power-up.

**Comment by r3vn** [comment]
Hello!
can you open the issue on https://github.com/droidian/meta please?
Also could you provide some more info about this? on which device is this happening?

G.
